"""Scenario task-type: creative multi-agent story generation."""

from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from config import logger

DEFAULT_SCENARIO_CRITERIA: dict[str, dict[str, Any]] = {
    "originality": {"weight": 0.3, "description": "Novel and surprising ideas"},
    "coherence": {"weight": 0.4, "description": "Logical flow and structure"},
    "engagement": {"weight": 0.3, "description": "Audience appeal and emotional impact"},
}


def get_default_criteria() -> dict:
    """Return default evaluation criteria for scenario task type."""
    return DEFAULT_SCENARIO_CRITERIA.copy()


async def send_to_studio(
    db: Session,
    session_id: int,
    storyboard_id: int | None = None,
    group_id: int = 1,
) -> dict[str, Any]:
    """Convert creative session output to storyboard scenes in Studio."""
    from models.creative import CreativeSession
    from models.scene import Scene
    from models.storyboard import Storyboard

    session = db.get(CreativeSession, session_id)
    if not session or not session.final_output:
        msg = f"Session {session_id} not found or not finalized"
        raise ValueError(msg)

    output = session.final_output
    content = output.get("content", "")

    # Create or use existing storyboard
    if storyboard_id:
        storyboard = db.get(Storyboard, storyboard_id)
        if not storyboard:
            msg = f"Storyboard {storyboard_id} not found"
            raise ValueError(msg)
    else:
        storyboard = Storyboard(
            title=output.get("title", f"Creative #{session_id}"),
            description=f"Generated by Creative Engine (session {session_id})",
            group_id=group_id,
        )
        db.add(storyboard)
        db.flush()

    # Parse content into scenes (split by double newline)
    scene_texts = [s.strip() for s in content.split("\n\n") if s.strip()]
    if not scene_texts:
        scene_texts = [content]

    existing_count = (
        db.query(Scene)
        .filter(Scene.storyboard_id == storyboard.id, Scene.deleted_at.is_(None))
        .count()
    )

    scenes_created = 0
    for i, text in enumerate(scene_texts):
        scene = Scene(
            storyboard_id=storyboard.id,
            order_index=existing_count + i,
            script_text=text,
        )
        db.add(scene)
        scenes_created += 1

    db.commit()
    logger.info(
        "[Creative] Session %d -> Storyboard %d: %d scenes created",
        session_id, storyboard.id, scenes_created,
    )

    return {
        "storyboard_id": storyboard.id,
        "scenes_created": scenes_created,
    }
