"""Tests for preview service (Phase 29 -- Video Pre-validation).

Covers:
- TTS cache key consistency (preview vs render pipeline)
- Single-scene TTS preview (cache hit, cache miss, voice resolution)
- Batch TTS preview (partial failure handling)
- Timeline calculation (sequential timing, speed multiplier)
- Pre-validation checks (missing images, empty scripts, duration)
"""

from __future__ import annotations

import hashlib
import io
import wave
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from schemas import (
    BatchTTSPreviewRequest,
    SceneTTSPreviewRequest,
    TimelineRequest,
    TimelineSceneInput,
)
from services.video.tts_helpers import tts_cache_key
from services.video.utils import clean_script_for_tts

# ── TTS Cache Key Consistency ─────────────────────────────


class TestTTSCacheKeyConsistency:
    """Cache key generated by preview must match render pipeline."""

    def test_same_input_same_key(self):
        """Identical inputs produce identical cache keys."""
        text = "안녕하세요, 테스트입니다."
        key1 = tts_cache_key(text, 1, "warm female voice", "korean")
        key2 = tts_cache_key(text, 1, "warm female voice", "korean")
        assert key1 == key2

    def test_different_text_different_key(self):
        """Different text produces different cache keys."""
        key1 = tts_cache_key("안녕하세요", 1, None, "korean")
        key2 = tts_cache_key("반갑습니다", 1, None, "korean")
        assert key1 != key2

    def test_different_preset_different_key(self):
        """Different voice_preset_id produces different cache keys."""
        key1 = tts_cache_key("안녕", 1, None, "korean")
        key2 = tts_cache_key("안녕", 2, None, "korean")
        assert key1 != key2

    def test_different_language_different_key(self):
        """Different language produces different cache keys."""
        key1 = tts_cache_key("hello", 1, None, "korean")
        key2 = tts_cache_key("hello", 1, None, "english")
        assert key1 != key2

    def test_different_voice_design_different_key(self):
        """Different voice_design_prompt produces different cache keys."""
        key1 = tts_cache_key("test", 1, "warm voice", "korean")
        key2 = tts_cache_key("test", 1, "cold voice", "korean")
        assert key1 != key2

    def test_none_voice_design_consistent(self):
        """None voice_design_prompt produces consistent keys."""
        key1 = tts_cache_key("test", None, None, "korean")
        key2 = tts_cache_key("test", None, None, "korean")
        assert key1 == key2

    def test_key_is_16_char_hex(self):
        """Cache key is a 16-character hex string (SHA-256 truncated)."""
        key = tts_cache_key("text", 1, "prompt", "korean")
        assert len(key) == 16
        assert all(c in "0123456789abcdef" for c in key)

    def test_key_matches_sha256_truncation(self):
        """Cache key matches manual SHA-256 calculation (includes naturalness suffix)."""
        from config import TTS_NATURALNESS_SUFFIX

        text, pid, design, lang, emotion = "hello", 1, "warm", "korean", ""
        # speaker=None → 빈 문자열
        parts = f"{text}|{pid}|{design}|{lang}|{emotion}||{TTS_NATURALNESS_SUFFIX}"
        expected = hashlib.sha256(parts.encode()).hexdigest()[:16]
        actual = tts_cache_key(text, pid, design, lang)
        assert actual == expected

    def test_cleaned_text_matches_render(self):
        """Preview cleans text same way as render, producing same cache key."""
        raw = "(한숨) 오늘도 힘든 하루였어..."
        cleaned = clean_script_for_tts(raw)
        # Preview and render both call clean_script_for_tts before tts_cache_key
        key = tts_cache_key(cleaned, None, None, "korean")
        assert len(key) == 16

    def test_none_preset_id_uses_none_string(self):
        """None preset_id is included as 'None' in the hash input."""
        from config import TTS_NATURALNESS_SUFFIX

        # speaker=None → 빈 문자열 (2번째 | 뒤)
        parts_none = f"test|{None}|{''}|korean|||{TTS_NATURALNESS_SUFFIX}"
        expected = hashlib.sha256(parts_none.encode()).hexdigest()[:16]
        actual = tts_cache_key("test", None, None, "korean")
        assert actual == expected


# ── Preview Scene TTS ─────────────────────────────────────


class TestPreviewSceneTTS:
    """Test preview_scene_tts service function."""

    @pytest.mark.asyncio
    async def test_empty_script_raises(self):
        """Empty script raises ValueError."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="", language="korean")
        mock_db = MagicMock()
        with pytest.raises(ValueError, match="TTS로 변환할 내용이 없습니다"):
            await preview_scene_tts(req, mock_db)

    @pytest.mark.asyncio
    async def test_whitespace_only_script_raises(self):
        """Whitespace-only script raises ValueError."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="   \n  ", language="korean")
        mock_db = MagicMock()
        with pytest.raises(ValueError, match="TTS로 변환할 내용이 없습니다"):
            await preview_scene_tts(req, mock_db)

    @pytest.mark.asyncio
    async def test_stage_direction_only_raises(self):
        """Script with only stage directions (non-speakable) raises ValueError."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="(한숨) (침묵)", language="korean")
        mock_db = MagicMock()
        with pytest.raises(ValueError, match="TTS로 변환할 내용이 없습니다"):
            await preview_scene_tts(req, mock_db)

    @pytest.mark.asyncio
    async def test_cache_hit_returns_cached(self, tmp_path):
        """When cache file exists, return cached=True without calling synthesize_tts."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="안녕하세요 테스트입니다.", language="korean")

        # Pre-compute cache key (speaker 포함)
        cleaned = clean_script_for_tts(req.script)
        cache_key = tts_cache_key(cleaned, None, None, "korean", speaker=req.speaker)

        # Create a minimal WAV file in the tmp cache dir
        wav_path = tmp_path / f"{cache_key}.wav"
        with wave.open(str(wav_path), "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)  # 1 second of silence

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://localhost:9000/test.wav"
        mock_asset.id = 1

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_scene_tts(req, mock_db)

        assert result.cached is True
        assert result.cache_key == cache_key
        assert result.duration > 0
        assert result.temp_asset_id == 1
        assert result.audio_url == "http://localhost:9000/test.wav"

    @pytest.mark.asyncio
    async def test_cache_miss_calls_synthesize(self, tmp_path):
        """When cache file does not exist, synthesize_tts is called."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="안녕하세요 테스트입니다.", language="korean")

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 42

        # Build minimal WAV bytes for the synthesize return
        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.0, True),
            ) as mock_synth,
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_scene_tts(req, mock_db)

        assert result.cached is False
        assert result.duration == 1.0
        assert result.temp_asset_id == 42
        mock_synth.assert_called_once()

        # Verify cache file was written (speaker 포함)
        cleaned = clean_script_for_tts(req.script)
        cache_key = tts_cache_key(cleaned, None, None, "korean", speaker=req.speaker)
        assert (tmp_path / f"{cache_key}.wav").exists()

    @pytest.mark.asyncio
    async def test_voice_preset_resolution(self, tmp_path):
        """voice_preset_id from storyboard speaker mapping is used."""
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(
            script="테스트 스크립트입니다.",
            speaker="narrator",
            storyboard_id=1,
            language="korean",
        )

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 99

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.video.tts_helpers.get_speaker_voice_preset",
                return_value=5,
            ) as mock_resolve,
            patch(
                "services.video.tts_helpers.get_preset_voice_info",
                return_value=("warm voice", 42),
            ),
            patch(
                "services.video.tts_helpers.translate_voice_prompt",
                return_value="warm voice",
            ),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.5, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_scene_tts(req, mock_db)

        mock_resolve.assert_called_once_with(1, "narrator")
        assert result.voice_seed == 42
        assert result.temp_asset_id == 99

    @pytest.mark.asyncio
    async def test_default_seed_when_no_preset(self, tmp_path):
        """TTS_DEFAULT_SEED is used when no voice preset is provided."""
        from config import TTS_DEFAULT_SEED
        from services.preview import preview_scene_tts

        req = SceneTTSPreviewRequest(script="기본 시드 테스트입니다.", language="korean")

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 1

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.0, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_scene_tts(req, mock_db)

        assert result.voice_seed == TTS_DEFAULT_SEED


# ── Batch TTS Preview ────────────────────────────────────


class TestPreviewBatchTTS:
    """Test batch TTS preview."""

    @pytest.mark.asyncio
    async def test_batch_partial_failure(self, tmp_path):
        """Batch should handle individual failures gracefully (empty script fails)."""
        from services.preview import preview_batch_tts

        req = BatchTTSPreviewRequest(
            scenes=[
                SceneTTSPreviewRequest(script="성공할 스크립트입니다.", language="korean"),
                SceneTTSPreviewRequest(script="", language="korean"),  # Will fail (empty)
            ],
        )

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 1

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 2.0, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_batch_tts(req, mock_db)

        assert len(result.items) == 2
        assert result.failed_count >= 1

        failed = [i for i in result.items if i.status == "failed"]
        assert len(failed) >= 1
        assert failed[0].error is not None

        success = [i for i in result.items if i.status in ("success", "cached")]
        assert len(success) >= 1

    @pytest.mark.asyncio
    async def test_batch_all_success(self, tmp_path):
        """Batch with valid scripts should all succeed."""
        from services.preview import preview_batch_tts

        req = BatchTTSPreviewRequest(
            scenes=[
                SceneTTSPreviewRequest(script="첫 번째 씬입니다.", language="korean"),
                SceneTTSPreviewRequest(script="두 번째 씬입니다.", language="korean"),
            ],
        )

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 1

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.5, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_batch_tts(req, mock_db)

        assert result.failed_count == 0
        assert result.generated_count == 2
        assert len(result.items) == 2
        assert result.total_duration > 0

    @pytest.mark.asyncio
    async def test_batch_global_storyboard_fallback(self, tmp_path):
        """Global storyboard_id is applied to scenes without their own."""
        from services.preview import preview_batch_tts

        req = BatchTTSPreviewRequest(
            scenes=[
                SceneTTSPreviewRequest(script="씬 하나입니다.", language="korean"),
            ],
            storyboard_id=10,
        )

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 1

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.video.tts_helpers.get_speaker_voice_preset",
                return_value=None,
            ),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.0, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_batch_tts(req, mock_db)

        assert result.failed_count == 0
        assert len(result.items) == 1

    @pytest.mark.asyncio
    async def test_batch_scene_order_preserved(self, tmp_path):
        """Batch results are sorted by scene_index."""
        from services.preview import preview_batch_tts

        req = BatchTTSPreviewRequest(
            scenes=[
                SceneTTSPreviewRequest(script="첫 번째 씬입니다.", language="korean"),
                SceneTTSPreviewRequest(script="두 번째 씬입니다.", language="korean"),
                SceneTTSPreviewRequest(script="세 번째 씬입니다.", language="korean"),
            ],
        )

        mock_db = MagicMock()
        mock_asset = MagicMock()
        mock_asset.url = "http://test.wav"
        mock_asset.id = 1

        wav_buf = io.BytesIO()
        with wave.open(wav_buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            wf.writeframes(b"\x00\x00" * 22050)
        wav_bytes = wav_buf.getvalue()

        with (
            patch("services.video.tts_helpers.TTS_CACHE_DIR", tmp_path),
            patch(
                "services.audio_client.synthesize_tts",
                new_callable=AsyncMock,
                return_value=(wav_bytes, 22050, 1.0, True),
            ),
            patch("services.preview_tts._save_audio_asset", return_value=mock_asset),
        ):
            result = await preview_batch_tts(req, mock_db)

        indices = [item.scene_index for item in result.items]
        assert indices == [0, 1, 2]


# ── Timeline Calculation ─────────────────────────────────


class TestPreviewTimeline:
    """Test timeline calculation."""

    def test_basic_timeline(self):
        """Basic timeline with TTS and non-TTS scenes."""
        from services.preview import preview_timeline

        req = TimelineRequest(
            scenes=[
                TimelineSceneInput(script="안녕하세요", duration=3.0, tts_duration=2.0),
                TimelineSceneInput(script="반갑습니다", duration=3.0, tts_duration=1.5),
                TimelineSceneInput(script="", duration=3.0, tts_duration=None),
            ],
            speed_multiplier=1.0,
        )

        result = preview_timeline(req)
        assert len(result.scenes) == 3
        assert result.total_duration > 0

        # Scenes should be sequential
        for i in range(1, len(result.scenes)):
            assert result.scenes[i].start_time == result.scenes[i - 1].end_time

    def test_empty_scenes(self):
        """Empty scene list produces zero duration."""
        from services.preview import preview_timeline

        req = TimelineRequest(scenes=[], speed_multiplier=1.0)
        result = preview_timeline(req)
        assert result.total_duration == 0
        assert len(result.scenes) == 0

    def test_speed_multiplier_affects_duration(self):
        """Higher speed multiplier reduces total duration."""
        from services.preview import preview_timeline

        scenes = [TimelineSceneInput(script="", duration=4.0, tts_duration=None)]

        slow = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=0.5))
        normal = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=1.0))
        fast = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=2.0))

        assert slow.total_duration > normal.total_duration
        assert normal.total_duration > fast.total_duration

    def test_tts_duration_extends_scene(self):
        """TTS duration extends scene when it exceeds base duration."""
        from services.preview import preview_timeline

        # Short base duration + long TTS should extend
        req = TimelineRequest(
            scenes=[
                TimelineSceneInput(script="긴 대사입니다", duration=2.0, tts_duration=5.0),
            ],
            speed_multiplier=1.0,
        )

        result = preview_timeline(req)
        assert result.scenes[0].has_tts is True
        # Effective duration should be at least the TTS duration
        assert result.scenes[0].effective_duration >= 5.0

    def test_no_tts_uses_base_duration(self):
        """Scene without TTS uses base duration / speed."""
        from services.preview import preview_timeline

        req = TimelineRequest(
            scenes=[
                TimelineSceneInput(script="", duration=4.0, tts_duration=None),
            ],
            speed_multiplier=1.0,
        )

        result = preview_timeline(req)
        assert result.scenes[0].has_tts is False
        assert result.scenes[0].effective_duration == 4.0

    def test_total_duration_equals_sum(self):
        """Total duration equals sum of effective durations."""
        from services.preview import preview_timeline

        req = TimelineRequest(
            scenes=[
                TimelineSceneInput(script="", duration=3.0, tts_duration=None),
                TimelineSceneInput(script="", duration=5.0, tts_duration=None),
            ],
            speed_multiplier=1.0,
        )

        result = preview_timeline(req)
        expected = sum(s.effective_duration for s in result.scenes)
        assert abs(result.total_duration - expected) < 0.01

    def test_start_end_times_consistent(self):
        """Each scene start_time == previous end_time."""
        from services.preview import preview_timeline

        req = TimelineRequest(
            scenes=[
                TimelineSceneInput(script="대사", duration=3.0, tts_duration=2.0),
                TimelineSceneInput(script="", duration=4.0, tts_duration=None),
                TimelineSceneInput(script="대사", duration=2.0, tts_duration=3.0),
            ],
            speed_multiplier=1.0,
        )

        result = preview_timeline(req)

        # First scene starts at 0
        assert result.scenes[0].start_time == 0.0

        for i in range(1, len(result.scenes)):
            assert result.scenes[i].start_time == result.scenes[i - 1].end_time

        # Last scene end_time equals total_duration
        assert result.scenes[-1].end_time == result.total_duration

    def test_speed_multiplier_clamped(self):
        """Speed multiplier is clamped between 0.25 and 2.0."""
        from services.preview import preview_timeline

        scenes = [TimelineSceneInput(script="", duration=4.0, tts_duration=None)]

        # Very low speed is clamped to 0.25
        very_slow = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=0.01))
        clamped_slow = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=0.25))

        assert very_slow.total_duration == clamped_slow.total_duration

        # Very high speed is clamped to 2.0
        very_fast = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=10.0))
        clamped_fast = preview_timeline(TimelineRequest(scenes=scenes, speed_multiplier=2.0))

        assert very_fast.total_duration == clamped_fast.total_duration


# ── Pre-validation ───────────────────────────────────────


class TestPreviewValidate:
    """Test pre-render validation checks."""

    @pytest.mark.asyncio
    async def test_missing_storyboard_raises_404(self):
        """Non-existent storyboard_id raises HTTPException(404)."""
        from fastapi import HTTPException

        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=9999)
        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = None

        with pytest.raises(HTTPException) as exc_info:
            await preview_validate(req, mock_db)
        assert exc_info.value.status_code == 404

    @pytest.mark.asyncio
    async def test_no_scenes_returns_error(self):
        """Storyboard with no scenes returns is_ready=False with error."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = []

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        result = await preview_validate(req, mock_db)

        assert result.is_ready is False
        assert result.total_scenes == 0
        assert any(issue.category == "scenes" and issue.level == "error" for issue in result.issues)

    @pytest.mark.asyncio
    async def test_missing_image_error(self, tmp_path):
        """Scene without image produces an error-level issue."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        mock_scene = MagicMock()
        mock_scene.order = 0
        mock_scene.image_asset_id = None
        mock_scene.candidates = []
        mock_scene.script = "테스트 대사입니다."
        mock_scene.duration = 3.0
        mock_scene.deleted_at = None

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = [mock_scene]

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        with patch("services.preview_validate.TTS_CACHE_DIR", tmp_path):
            result = await preview_validate(req, mock_db)

        assert result.is_ready is False
        image_errors = [i for i in result.issues if i.category == "image" and i.level == "error"]
        assert len(image_errors) == 1

    @pytest.mark.asyncio
    async def test_empty_script_warning(self, tmp_path):
        """Scene with empty script produces a warning."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        mock_scene = MagicMock()
        mock_scene.order = 0
        mock_scene.image_asset_id = 10  # Has image
        mock_scene.candidates = []
        mock_scene.script = ""
        mock_scene.duration = 3.0
        mock_scene.deleted_at = None

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = [mock_scene]

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        with patch("services.preview_validate.TTS_CACHE_DIR", tmp_path):
            result = await preview_validate(req, mock_db)

        # Empty script is a warning, not an error
        assert result.is_ready is True
        script_warnings = [i for i in result.issues if i.category == "script" and i.level == "warning"]
        assert len(script_warnings) == 1

    @pytest.mark.asyncio
    async def test_long_script_warning(self, tmp_path):
        """Script over 500 chars produces a warning."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        mock_scene = MagicMock()
        mock_scene.order = 0
        mock_scene.image_asset_id = 10
        mock_scene.candidates = []
        mock_scene.script = "가" * 501  # Over 500 chars
        mock_scene.duration = 3.0
        mock_scene.deleted_at = None

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = [mock_scene]

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        with patch("services.preview_validate.TTS_CACHE_DIR", tmp_path):
            result = await preview_validate(req, mock_db)

        script_warnings = [
            i for i in result.issues if i.category == "script" and i.level == "warning" and "매우 깁니다" in i.message
        ]
        assert len(script_warnings) == 1

    @pytest.mark.asyncio
    async def test_duration_over_60s_warning(self, tmp_path):
        """Total duration > 60s produces a warning."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        # Create enough scenes to exceed 60s
        scenes = []
        for idx in range(21):
            mock_scene = MagicMock()
            mock_scene.order = idx
            mock_scene.image_asset_id = 10
            mock_scene.candidates = []
            mock_scene.script = "테스트 대사입니다."
            mock_scene.duration = 3.0  # 21 * 3 = 63s > 60s
            mock_scene.deleted_at = None
            scenes.append(mock_scene)

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = scenes

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        with patch("services.preview_validate.TTS_CACHE_DIR", tmp_path):
            result = await preview_validate(req, mock_db)

        duration_warnings = [i for i in result.issues if i.category == "duration" and i.level == "warning"]
        assert len(duration_warnings) == 1
        assert "60초를 초과합니다" in duration_warnings[0].message

    @pytest.mark.asyncio
    async def test_all_valid_returns_ready(self, tmp_path):
        """Valid storyboard with images returns is_ready=True."""
        from schemas import PreValidateRequest
        from services.preview import preview_validate

        req = PreValidateRequest(storyboard_id=1)

        mock_scene = MagicMock()
        mock_scene.order = 0
        mock_scene.image_asset_id = 10  # Has image
        mock_scene.candidates = []
        mock_scene.script = "테스트 대사입니다."
        mock_scene.duration = 3.0
        mock_scene.deleted_at = None

        mock_storyboard = MagicMock()
        mock_storyboard.deleted_at = None
        mock_storyboard.scenes = [mock_scene]

        mock_db = MagicMock()
        mock_db.query.return_value.options.return_value.filter.return_value.first.return_value = mock_storyboard

        with patch("services.preview_validate.TTS_CACHE_DIR", tmp_path):
            result = await preview_validate(req, mock_db)

        assert result.is_ready is True
        assert result.total_scenes == 1
        # No error-level issues
        errors = [i for i in result.issues if i.level == "error"]
        assert len(errors) == 0


# ── WAV Duration Helper ──────────────────────────────────


class TestWavDuration:
    """Test _wav_duration helper."""

    def test_calculates_correct_duration(self):
        """WAV duration is correctly calculated from bytes."""
        from services.video.tts_helpers import _wav_duration

        buf = io.BytesIO()
        with wave.open(buf, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(44100)
            wf.writeframes(b"\x00\x00" * 44100 * 2)  # 2 seconds

        duration = _wav_duration(buf.getvalue())
        assert abs(duration - 2.0) < 0.01

    def test_stereo_wav(self):
        """Stereo WAV duration is correctly calculated."""
        from services.video.tts_helpers import _wav_duration

        buf = io.BytesIO()
        with wave.open(buf, "w") as wf:
            wf.setnchannels(2)
            wf.setsampwidth(2)
            wf.setframerate(22050)
            # 2 channels * 2 bytes/sample * 22050 samples = 1 second
            wf.writeframes(b"\x00\x00" * 22050 * 2)

        duration = _wav_duration(buf.getvalue())
        assert abs(duration - 1.0) < 0.01


# ── Pre-validation API Integration ───────────────────────


class TestPreviewValidateAPI:
    """API integration tests for POST /preview/validate."""

    def test_nonexistent_storyboard_returns_404(self, client):
        """존재하지 않는 storyboard_id로 요청 시 404를 반환한다."""
        from tests.conftest import SVC

        resp = client.post(
            f"{SVC}/preview/validate",
            json={"storyboard_id": 99999},
        )
        assert resp.status_code == 404
