#!/bin/bash
# Playwright QA 순찰 — 핵심 플로우 자동 테스트 → 실패 시 GitHub Issue 생성
# 사용법: ./scripts/sdd-qa.sh
#
# 전제조건:
#   - Frontend (localhost:3000) 실행 중
#   - Backend (localhost:8000) 실행 중
#   - Playwright 브라우저 설치 완료

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="${PROJECT_DIR}/frontend"
GITHUB_LABEL="qa-patrol"
ASSIGNEE="stopper2008"
RESULTS_DIR="/tmp/qa-patrol-results"
TIMESTAMP=$(date +"%Y-%m-%d_%H%M%S")

# --- Slack 알림 함수 (notify.py CLI) ---
ORCH_DIR="$PROJECT_DIR/orchestrator"
notify_slack() {
  local msg="$1"
  local level="${2:-info}"
  local link_text="${3:-}"
  local link_url="${4:-}"
  local -a link_flag=()
  if [[ -n "$link_text" && -n "$link_url" ]]; then
    link_flag=("--link" "$link_text" "$link_url")
  fi
  cd "$ORCH_DIR" && uv run python -m orchestrator.tools.notify "$msg" \
    --level "$level" "${link_flag[@]}" 2>&1 | grep -v "^$" >&2 || true
}

echo "=== QA Patrol ==="
echo "시작: $(date)"
echo ""

# --- 서비스 상태 확인 ---
echo "[1/4] 서비스 상태 확인..."

BACKEND_OK=false
FRONTEND_OK=false

if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
  BACKEND_OK=true
  echo "  Backend (8000): OK"
else
  echo "  Backend (8000): DOWN"
fi

if curl -sf -o /dev/null http://localhost:3000/ 2>&1; then
  FRONTEND_OK=true
  echo "  Frontend (3000): OK"
else
  echo "  Frontend (3000): DOWN"
fi

if [[ "$BACKEND_OK" == false ]] || [[ "$FRONTEND_OK" == false ]]; then
  echo ""
  echo "[ERROR] 서비스가 실행 중이 아닙니다. 순찰 중단."

  # 서비스 다운 자체를 이슈로 등록
  SERVICES_DOWN=""
  [[ "$BACKEND_OK" == false ]] && SERVICES_DOWN="${SERVICES_DOWN}Backend "
  [[ "$FRONTEND_OK" == false ]] && SERVICES_DOWN="${SERVICES_DOWN}Frontend "

  # 중복 체크: 최근 24시간 내 같은 서비스 다운 이슈가 있는지
  EXISTING=$(gh issue list --label "$GITHUB_LABEL" --state open --limit 10 --json title 2>/dev/null | \
    jq -r ".[].title" 2>/dev/null | grep -c "서비스 다운" || echo "0")

  if [[ "$EXISTING" -eq 0 ]]; then
    gh issue create \
      --title "[QA Patrol] 서비스 다운 감지: ${SERVICES_DOWN}" \
      --body "$(cat <<EOF
## QA Patrol — 서비스 다운 감지

| 서비스 | 상태 |
|--------|------|
| Backend (8000) | $([ "$BACKEND_OK" == true ] && echo "OK" || echo "DOWN") |
| Frontend (3000) | $([ "$FRONTEND_OK" == true ] && echo "OK" || echo "DOWN") |

**감지 시각**: $(date)

순찰 테스트를 실행할 수 없습니다. 서비스 복구 후 재실행하세요.

---
*Auto-generated by qa-patrol*
EOF
)" \
      --label "$GITHUB_LABEL" \
      --label "bug" \
      --assignee "$ASSIGNEE" 2>/dev/null && echo "  GitHub Issue 생성 완료"
  else
    echo "  서비스 다운 이슈가 이미 열려 있어 스킵합니다."
  fi

  notify_slack "[QA Patrol] 서비스 다운 감지: ${SERVICES_DOWN}" "critical"
  exit 1
fi

# --- Playwright 테스트 실행 ---
echo ""
echo "[2/4] Playwright QA 순찰 실행..."

mkdir -p "$RESULTS_DIR"

cd "$FRONTEND_DIR"

# qa-patrol.spec.ts만 실행 (JSON reporter + 스크린샷)
npx playwright test e2e/qa-patrol.spec.ts \
  --config=playwright.e2e.config.ts \
  --reporter=json \
  --output="${RESULTS_DIR}/artifacts" \
  > "${RESULTS_DIR}/results_${TIMESTAMP}.json" 2>"${RESULTS_DIR}/stderr_${TIMESTAMP}.log"

TEST_EXIT=$?

echo ""
echo "[3/4] 결과 분석..."

if [[ $TEST_EXIT -eq 0 ]]; then
  echo "  모든 테스트 통과 — 이상 없음"
  echo ""
  echo "[4/4] 완료"
  notify_slack "[QA Patrol] 4/4 통과, 이상 없음" "info"
  echo "=== QA Patrol 종료 (정상) ==="
  exit 0
fi

# --- 실패 분석 + GitHub Issue 생성 ---
echo "  테스트 실패 감지 (exit code: ${TEST_EXIT})"

# JSON 결과에서 실패 테스트 추출
RESULT_FILE="${RESULTS_DIR}/results_${TIMESTAMP}.json"

if [[ -f "$RESULT_FILE" ]]; then
  FAILED_TESTS=$(jq -r '
    .suites[]?.specs[]? |
    select(.ok == false) |
    "- **\(.title)**: \(.tests[0]?.results[0]?.error?.message // "unknown error" | split("\n")[0])"
  ' "$RESULT_FILE" 2>/dev/null || echo "- (결과 파싱 실패)")
else
  FAILED_TESTS="- (결과 파일 없음)"
fi

FAILED_COUNT=$(echo "$FAILED_TESTS" | grep -c "^\-" || echo "0")

echo "  실패 테스트: ${FAILED_COUNT}건"

# 중복 체크: 같은 날짜 QA 순찰 이슈가 이미 있는지
TODAY=$(date +"%Y-%m-%d")
EXISTING_TODAY=$(gh issue list --label "$GITHUB_LABEL" --state open --limit 10 --json title 2>/dev/null | \
  jq -r ".[].title" 2>/dev/null | grep -c "${TODAY}" || echo "0")

if [[ "$EXISTING_TODAY" -gt 0 ]]; then
  echo "  오늘 이미 QA 순찰 이슈가 열려 있어 스킵합니다."
else
  echo ""
  echo "[4/4] GitHub Issue 생성..."

  # 스크린샷 목록 (있으면)
  SCREENSHOTS=""
  if ls "${RESULTS_DIR}/artifacts/"*.png 2>/dev/null; then
    SCREENSHOTS="스크린샷이 \`${RESULTS_DIR}/artifacts/\`에 저장되었습니다."
  fi

  gh issue create \
    --title "[QA Patrol] ${TODAY} 순찰 실패 — ${FAILED_COUNT}건" \
    --body "$(cat <<EOF
## QA Patrol 결과 — ${TODAY}

### 실패 테스트
${FAILED_TESTS}

### 환경
| 항목 | 값 |
|------|-----|
| **시각** | $(date) |
| **Backend** | OK |
| **Frontend** | OK |

### 상세 로그
\`${RESULT_FILE}\`

${SCREENSHOTS}

---
*Auto-generated by qa-patrol*
EOF
)" \
    --label "$GITHUB_LABEL" \
    --label "bug" \
    --assignee "$ASSIGNEE" 2>/dev/null && echo "  GitHub Issue 생성 완료"
fi

# --- Slack 알림 ---
QA_ISSUES_URL="https://github.com/tomo-playground/shorts-producer/issues?q=label%3Aqa-patrol+is%3Aopen"
notify_slack "[QA Patrol] 테스트 실패 ${FAILED_COUNT}건" "warning" \
  "QA Issues" "$QA_ISSUES_URL"

echo "=== QA Patrol 종료 (실패 ${FAILED_COUNT}건) ==="
exit $TEST_EXIT
