#!/bin/bash
# Sentry 에러 배치 순찰 — 새 이슈 수집 → GitHub Issue 자동 생성
# 사용법: ./scripts/sdd-sentry.sh [--since HOURS]
#
# 환경변수:
#   SENTRY_AUTH_TOKEN  — Sentry API Bearer token (필수)
#
# 기본: 최근 24시간 내 새 이슈 조회
# --since 48  → 최근 48시간

set -euo pipefail

SENTRY_ORG="tomo-playground"
SENTRY_PROJECTS=("shorts-producer-backend" "shorts-producer-frontend" "shorts-producer-audio")
PROJECT_LABELS=("backend" "frontend" "audio")
SENTRY_API="https://sentry.io/api/0"
GITHUB_LABEL="sentry"
ASSIGNEE="stopper2008"
SINCE_HOURS=24

# --- 인자 파싱 ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE_HOURS="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- 환경변수 검증 ---
# backend/.env에서 자동 로드
if [[ -z "${SENTRY_AUTH_TOKEN:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
  ENV_FILE="${SCRIPT_DIR}/../backend/.env"
  if [[ -f "$ENV_FILE" ]]; then
    SENTRY_AUTH_TOKEN=$(grep '^SENTRY_AUTH_TOKEN=' "$ENV_FILE" | cut -d'=' -f2- | tr -d "'\"")
    export SENTRY_AUTH_TOKEN
  fi
fi

if [[ -z "${SENTRY_AUTH_TOKEN:-}" ]]; then
  echo "[ERROR] SENTRY_AUTH_TOKEN 환경변수가 설정되지 않았습니다."
  echo "  export SENTRY_AUTH_TOKEN='sntrys_...'"
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "[ERROR] gh CLI가 설치되어 있지 않습니다."
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "[ERROR] jq가 설치되어 있지 않습니다."
  exit 1
fi

# --- Slack 알림 함수 ---
notify_slack() {
  local text="$1"
  if [[ -n "${SLACK_WEBHOOK_URL:-}" ]]; then
    curl -sf -X POST "$SLACK_WEBHOOK_URL" \
      -H 'Content-Type: application/json' \
      -d "{\"text\": \"${text}\"}" >/dev/null 2>&1 || true
  fi
}

# --- 시간 계산 ---
SINCE_ISO=$(date -u -d "${SINCE_HOURS} hours ago" +"%Y-%m-%dT%H:%M:%S" 2>/dev/null \
  || date -u -v-"${SINCE_HOURS}"H +"%Y-%m-%dT%H:%M:%S")

echo "=== Sentry Patrol ==="
echo "조회 범위: ${SINCE_HOURS}시간 전 ~ 현재 (since: ${SINCE_ISO})"
echo ""

TOTAL_NEW=0
TOTAL_SKIPPED=0
TOTAL_CREATED=0

# --- 기존 GitHub Issues에서 Sentry ID 목록 캐싱 ---
echo "[1/3] 기존 GitHub Issues (label:${GITHUB_LABEL}) 조회 중..."
EXISTING_ISSUES=$(gh issue list --label "$GITHUB_LABEL" --state all --limit 500 --json title,body 2>/dev/null || echo "[]")

# Sentry Issue ID 추출 (본문의 sentry-id: 필드에서)
EXISTING_SENTRY_IDS=$(echo "$EXISTING_ISSUES" | jq -r '.[].body // "" | capture("sentry-id: (?<id>[0-9]+)") | .id' 2>/dev/null || echo "")

is_duplicate() {
  local sentry_id="$1"
  echo "$EXISTING_SENTRY_IDS" | grep -qx "$sentry_id" 2>/dev/null
}

# --- 프로젝트별 순회 ---
echo "[2/3] Sentry 프로젝트 순회 시작..."
echo ""

for i in "${!SENTRY_PROJECTS[@]}"; do
  project="${SENTRY_PROJECTS[$i]}"
  project_label="${PROJECT_LABELS[$i]}"

  echo "--- ${project} ---"

  # 새 이슈 조회 (firstSeen 기준)
  ISSUES_JSON=$(curl -sf \
    -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
    "${SENTRY_API}/projects/${SENTRY_ORG}/${project}/issues/?query=is:unresolved&sort=date&limit=25" \
    2>/dev/null || echo "[]")

  if [[ "$ISSUES_JSON" == "[]" ]] || [[ -z "$ISSUES_JSON" ]]; then
    echo "  이슈 없음 (또는 API 오류)"
    continue
  fi

  # firstSeen 기준 필터링
  FILTERED=$(echo "$ISSUES_JSON" | jq --arg since "$SINCE_ISO" \
    '[.[] | select(.firstSeen >= $since)]')

  COUNT=$(echo "$FILTERED" | jq 'length')
  echo "  새 이슈: ${COUNT}건"
  TOTAL_NEW=$((TOTAL_NEW + COUNT))

  if [[ "$COUNT" -eq 0 ]]; then
    continue
  fi

  # 각 이슈 처리 (process substitution으로 서브셸 방지)
  while IFS= read -r issue; do
    SENTRY_ID=$(echo "$issue" | jq -r '.id')
    TITLE=$(echo "$issue" | jq -r '.title')
    CULPRIT=$(echo "$issue" | jq -r '.culprit // "unknown"')
    FIRST_SEEN=$(echo "$issue" | jq -r '.firstSeen')
    LAST_SEEN=$(echo "$issue" | jq -r '.lastSeen')
    EVENT_COUNT=$(echo "$issue" | jq -r '.count')
    LEVEL=$(echo "$issue" | jq -r '.level // "error"')
    PERMALINK=$(echo "$issue" | jq -r '.permalink')

    # 중복 체크 (조용히 스킵)
    if is_duplicate "$SENTRY_ID"; then
      TOTAL_SKIPPED=$((TOTAL_SKIPPED + 1))
      continue
    fi

    # 최신 이벤트 상세 조회 (스택트레이스)
    LATEST_EVENT=$(curl -sf \
      -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
      "${SENTRY_API}/issues/${SENTRY_ID}/events/latest/" \
      2>/dev/null || echo "{}")

    # 스택트레이스 추출
    STACKTRACE=""
    if [[ "$LATEST_EVENT" != "{}" ]]; then
      STACKTRACE=$(echo "$LATEST_EVENT" | jq -r '
        .entries[]? |
        select(.type == "exception") |
        .data.values[]? |
        "\(.type): \(.value)\n" +
        ([.stacktrace.frames[]? |
          select(.inApp == true) |
          "  \(.filename):\(.lineNo) in \(.function // "?")"
        ] | reverse | join("\n"))
      ' 2>/dev/null || echo "")
    fi

    # GitHub Issue 본문 구성
    ISSUE_BODY=$(cat <<EOF
## Sentry Error Report

| 항목 | 값 |
|------|-----|
| **Project** | \`${project}\` |
| **Level** | ${LEVEL} |
| **발생 횟수** | ${EVENT_COUNT}회 |
| **최초 발생** | ${FIRST_SEEN} |
| **최근 발생** | ${LAST_SEEN} |
| **위치** | \`${CULPRIT}\` |
| **Sentry Link** | [${SENTRY_ID}](${PERMALINK}) |

<!-- sentry-id: ${SENTRY_ID} -->

### Stack Trace

\`\`\`
${STACKTRACE:-"(스택트레이스 조회 불가)"}
\`\`\`

---
*Auto-generated by sentry-patrol*
EOF
)

    # GitHub Issue 생성
    ISSUE_TITLE="[Sentry] ${project_label}: ${TITLE}"
    # 제목 길이 제한 (256자)
    if [[ ${#ISSUE_TITLE} -gt 256 ]]; then
      ISSUE_TITLE="${ISSUE_TITLE:0:253}..."
    fi

    gh issue create \
      --title "$ISSUE_TITLE" \
      --body "$ISSUE_BODY" \
      --label "$GITHUB_LABEL" \
      --label "bug" \
      --assignee "$ASSIGNEE" \
      2>/dev/null && {
        echo "  [CREATED] #${SENTRY_ID}: ${TITLE}"
        TOTAL_CREATED=$((TOTAL_CREATED + 1))
      } || {
        echo "  [FAIL] #${SENTRY_ID}: ${TITLE} — GitHub Issue 생성 실패"
      }

  done < <(echo "$FILTERED" | jq -c '.[]')
done

echo ""
echo "[3/3] 완료"
echo "  새 이슈: ${TOTAL_NEW}건"
echo "  스킵 (중복): ${TOTAL_SKIPPED}건"
echo "  생성: ${TOTAL_CREATED}건"
echo "=== Sentry Patrol 종료 ==="

# --- Slack 알림 ---
if [[ "$TOTAL_CREATED" -gt 0 ]]; then
  notify_slack ":rotating_light: *Sentry Patrol* — 새 에러 ${TOTAL_CREATED}건 감지\n조회: ${TOTAL_NEW}건 | 중복 스킵: ${TOTAL_SKIPPED}건 | *신규 Issue: ${TOTAL_CREATED}건*\nhttps://github.com/tomo-playground/shorts-producer/issues?q=label%3Asentry+is%3Aopen"
else
  notify_slack ":white_check_mark: *Sentry Patrol* — 이상 없음\n조회: ${TOTAL_NEW}건 | 중복 스킵: ${TOTAL_SKIPPED}건 | 신규: 0건"
fi
