"""Add project group and media asset models

Revision ID: 12bda4470e3e
Revises: 653ba7d1613b
Create Date: 2026-01-31 02:36:15.348110

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "12bda4470e3e"
down_revision: str | Sequence[str] | None = "653ba7d1613b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
