"""Add gemini_usage_logs table for image editing cost tracking

Revision ID: 1764bb5dfc16
Revises: g3h4i5j6k7l8
Create Date: 2026-01-27 15:59:16.491864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1764bb5dfc16'
down_revision: Union[str, Sequence[str], None] = 'g3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('scene_index', sa.Integer(), nullable=True),
    sa.Column('edit_type', sa.String(length=20), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=True),
    sa.Column('target_change', sa.Text(), nullable=False),
    sa.Column('before_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preserve_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('match_rate_before', sa.Float(), nullable=True),
    sa.Column('match_rate_after', sa.Float(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('vision_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemini_usage_logs_cost_usd'), 'gemini_usage_logs', ['cost_usd'], unique=False)
    op.create_index(op.f('ix_gemini_usage_logs_edit_type'), 'gemini_usage_logs', ['edit_type'], unique=False)
    op.create_index(op.f('ix_gemini_usage_logs_project_name'), 'gemini_usage_logs', ['project_name'], unique=False)
    op.create_index(op.f('ix_gemini_usage_logs_scene_index'), 'gemini_usage_logs', ['scene_index'], unique=False)
    op.create_index(op.f('ix_gemini_usage_logs_status'), 'gemini_usage_logs', ['status'], unique=False)
    op.drop_index(op.f('ix_generation_logs_project'), table_name='generation_logs')
    op.create_index(op.f('ix_generation_logs_project_name'), 'generation_logs', ['project_name'], unique=False)
    op.drop_index(op.f('ix_scene_quality_match_rate'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_project'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_scene_id'), table_name='scene_quality_scores')
    op.create_index(op.f('ix_scene_quality_scores_match_rate'), 'scene_quality_scores', ['match_rate'], unique=False)
    op.create_index(op.f('ix_scene_quality_scores_project_name'), 'scene_quality_scores', ['project_name'], unique=False)
    op.create_index(op.f('ix_scene_quality_scores_scene_id'), 'scene_quality_scores', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_quality_scores_scene_id'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_scores_project_name'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_scores_match_rate'), table_name='scene_quality_scores')
    op.create_index(op.f('ix_scene_quality_scene_id'), 'scene_quality_scores', ['scene_id'], unique=False)
    op.create_index(op.f('ix_scene_quality_project'), 'scene_quality_scores', ['project_name'], unique=False)
    op.create_index(op.f('ix_scene_quality_match_rate'), 'scene_quality_scores', ['match_rate'], unique=False)
    op.drop_index(op.f('ix_generation_logs_project_name'), table_name='generation_logs')
    op.create_index(op.f('ix_generation_logs_project'), 'generation_logs', ['project_name'], unique=False)
    op.drop_index(op.f('ix_gemini_usage_logs_status'), table_name='gemini_usage_logs')
    op.drop_index(op.f('ix_gemini_usage_logs_scene_index'), table_name='gemini_usage_logs')
    op.drop_index(op.f('ix_gemini_usage_logs_project_name'), table_name='gemini_usage_logs')
    op.drop_index(op.f('ix_gemini_usage_logs_edit_type'), table_name='gemini_usage_logs')
    op.drop_index(op.f('ix_gemini_usage_logs_cost_usd'), table_name='gemini_usage_logs')
    op.drop_table('gemini_usage_logs')
    # ### end Alembic commands ###
