"""add preview_locked to characters

Revision ID: 1f60e2603354
Revises: ac66dee829e6
Create Date: 2026-02-01 01:51:33.422848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f60e2603354'
down_revision: Union[str, Sequence[str], None] = 'ac66dee829e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('preview_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'preview_locked')
    # ### end Alembic commands ###
