"""retry_remove_activity_log_fk

Revision ID: 25a8497bf2cb
Revises: ec0ed3c9015d
Create Date: 2026-01-31 21:18:32.340671

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '25a8497bf2cb'
down_revision: str | Sequence[str] | None = 'ec0ed3c9015d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'storyboard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('activity_logs_storyboard_id_fkey'), 'activity_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('activity_logs_storyboard_id_fkey'), 'activity_logs', 'storyboards', ['storyboard_id'], ['id'])
    op.alter_column('activity_logs', 'storyboard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
