"""drop_legacy_url_columns

Revision ID: 4249c8f1cd5c
Revises: ca169902f4a4
Create Date: 2026-01-31 11:20:24.838367

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4249c8f1cd5c"
down_revision: str | Sequence[str] | None = "ca169902f4a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "preview_image_url")
    op.drop_column("loras", "preview_image_url")
    op.drop_column("projects", "avatar_url")
    op.drop_column("scenes", "image_url")
    op.drop_column("sd_models", "preview_image_url")
    op.drop_column("storyboards", "video_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("storyboards", sa.Column("video_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column(
        "sd_models", sa.Column("preview_image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True)
    )
    op.add_column("scenes", sa.Column("image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column("projects", sa.Column("avatar_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column("loras", sa.Column("preview_image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column(
        "characters", sa.Column("preview_image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
