"""add_storyboard_id_to_logs_and_scores

Revision ID: 42fc6b015f1a
Revises: c745c3e5f955
Create Date: 2026-01-30 09:44:26.886795

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42fc6b015f1a"
down_revision: str | Sequence[str] | None = "c745c3e5f955"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity_logs", sa.Column("storyboard_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_activity_logs_storyboard_id"), "activity_logs", ["storyboard_id"], unique=False)
    op.create_foreign_key(None, "activity_logs", "storyboards", ["storyboard_id"], ["id"])
    op.add_column("scene_quality_scores", sa.Column("storyboard_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_scene_quality_scores_storyboard_id"), "scene_quality_scores", ["storyboard_id"], unique=False
    )
    op.create_foreign_key(None, "scene_quality_scores", "storyboards", ["storyboard_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scene_quality_scores", type_="foreignkey")
    op.drop_index(op.f("ix_scene_quality_scores_storyboard_id"), table_name="scene_quality_scores")
    op.drop_column("scene_quality_scores", "storyboard_id")
    op.drop_constraint(None, "activity_logs", type_="foreignkey")
    op.drop_index(op.f("ix_activity_logs_storyboard_id"), table_name="activity_logs")
    op.drop_column("activity_logs", "storyboard_id")
    # ### end Alembic commands ###
