"""add character ip adapter fields

Revision ID: 4b10d9934045
Revises: df9af51fe523
Create Date: 2026-01-27 18:20:22.684379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b10d9934045'
down_revision: Union[str, Sequence[str], None] = 'df9af51fe523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('ip_adapter_weight', sa.Float(), nullable=True))
    op.add_column('characters', sa.Column('ip_adapter_model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'ip_adapter_model')
    op.drop_column('characters', 'ip_adapter_weight')
    # ### end Alembic commands ###
