"""Add TagRule and SceneQualityScore

Revision ID: 5d4569272d9e
Revises: 68d77e9ac733
Create Date: 2026-01-28 23:51:32.975804

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d4569272d9e'
down_revision: str | Sequence[str] | None = '68d77e9ac733'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('match_rate', sa.Float(), nullable=True),
    sa.Column('matched_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_quality_scores_match_rate'), 'scene_quality_scores', ['match_rate'], unique=False)
    op.create_index(op.f('ix_scene_quality_scores_project_name'), 'scene_quality_scores', ['project_name'], unique=False)
    op.create_index(op.f('ix_scene_quality_scores_scene_id'), 'scene_quality_scores', ['scene_id'], unique=False)
    op.create_table('tag_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('source_tag_id', sa.Integer(), nullable=False),
    sa.Column('target_tag_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_rules_source_tag_id'), 'tag_rules', ['source_tag_id'], unique=False)
    op.create_index(op.f('ix_tag_rules_target_tag_id'), 'tag_rules', ['target_tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_rules_target_tag_id'), table_name='tag_rules')
    op.drop_index(op.f('ix_tag_rules_source_tag_id'), table_name='tag_rules')
    op.drop_table('tag_rules')
    op.drop_index(op.f('ix_scene_quality_scores_scene_id'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_scores_project_name'), table_name='scene_quality_scores')
    op.drop_index(op.f('ix_scene_quality_scores_match_rate'), table_name='scene_quality_scores')
    op.drop_table('scene_quality_scores')
    # ### end Alembic commands ###
