"""add character reference prompt fields

Revision ID: 616895d11269
Revises: 4b10d9934045
Create Date: 2026-01-27 19:17:23.411243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616895d11269'
down_revision: Union[str, Sequence[str], None] = '4b10d9934045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('reference_base_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('reference_negative_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'reference_negative_prompt')
    op.drop_column('characters', 'reference_base_prompt')
    # ### end Alembic commands ###
