"""Add Gemini auto-edit tracking to activity_logs

Revision ID: 653ba7d1613b
Revises: 59c63582ece4
Create Date: 2026-01-31 02:22:11.417188

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '653ba7d1613b'
down_revision: str | Sequence[str] | None = '59c63582ece4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('gemini_edited', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('activity_logs', sa.Column('gemini_cost_usd', sa.Float(), nullable=True))
    op.add_column('activity_logs', sa.Column('original_match_rate', sa.Float(), nullable=True))
    op.add_column('activity_logs', sa.Column('final_match_rate', sa.Float(), nullable=True))
    op.create_index(op.f('ix_activity_logs_gemini_edited'), 'activity_logs', ['gemini_edited'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_gemini_edited'), table_name='activity_logs')
    op.drop_column('activity_logs', 'final_match_rate')
    op.drop_column('activity_logs', 'original_match_rate')
    op.drop_column('activity_logs', 'gemini_cost_usd')
    op.drop_column('activity_logs', 'gemini_edited')
    # ### end Alembic commands ###
