"""Add classification fields to tags

Revision ID: 68d77e9ac733
Revises: f691fbaa1e51
Create Date: 2026-01-28 23:45:14.884007

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68d77e9ac733'
down_revision: str | Sequence[str] | None = 'f691fbaa1e51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.String(length=100), nullable=False),
    sa.Column('target_group', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sd_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('match_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_match_rate'), 'generation_logs', ['match_rate'], unique=False)
    op.create_index(op.f('ix_generation_logs_project_name'), 'generation_logs', ['project_name'], unique=False)
    op.create_index(op.f('ix_generation_logs_scene_index'), 'generation_logs', ['scene_index'], unique=False)
    op.add_column('tags', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('tags', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tags', sa.Column('group_name', sa.String(length=50), nullable=True))
    op.add_column('tags', sa.Column('classification_source', sa.String(length=20), nullable=True))
    op.add_column('tags', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('tags', sa.Column('priority', sa.Integer(), nullable=False, server_default='100'))
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_column('tags', 'priority')
    op.drop_column('tags', 'classification_confidence')
    op.drop_column('tags', 'classification_source')
    op.drop_column('tags', 'group_name')
    op.drop_column('tags', 'description')
    op.drop_column('tags', 'category')
    op.drop_index(op.f('ix_generation_logs_scene_index'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_project_name'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_match_rate'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_table('classification_rules')
    # ### end Alembic commands ###
