"""add candidates to scenes

Revision ID: 7bdbef2edb37
Revises: 12bda4470e3e
Create Date: 2026-01-31 09:06:40.131187

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bdbef2edb37'
down_revision: str | Sequence[str] | None = '12bda4470e3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'candidates')
    # ### end Alembic commands ###
