"""add_lora_calibration_fields

Revision ID: 8adf3722a9ff
Revises: e1f2g3h4i5j6
Create Date: 2026-01-25 08:29:04.948607

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8adf3722a9ff'
down_revision: str | Sequence[str] | None = 'e1f2g3h4i5j6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loras', sa.Column('lora_type', sa.String(length=20), nullable=True))
    op.add_column('loras', sa.Column('optimal_weight', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('loras', sa.Column('calibration_score', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loras', 'calibration_score')
    op.drop_column('loras', 'optimal_weight')
    op.drop_column('loras', 'lora_type')
    # ### end Alembic commands ###
