"""Drop generation_logs table

Revision ID: 9809a1824ca3
Revises: 5d4569272d9e
Create Date: 2026-01-28 23:59:51.167044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9809a1824ca3'
down_revision: Union[str, Sequence[str], None] = '5d4569272d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_logs_match_rate'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_project_name'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_scene_index'), table_name='generation_logs')
    op.drop_table('generation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('scene_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sd_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seed', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('match_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_logs_pkey'))
    )
    op.create_index(op.f('ix_generation_logs_scene_index'), 'generation_logs', ['scene_index'], unique=False)
    op.create_index(op.f('ix_generation_logs_project_name'), 'generation_logs', ['project_name'], unique=False)
    op.create_index(op.f('ix_generation_logs_match_rate'), 'generation_logs', ['match_rate'], unique=False)
    # ### end Alembic commands ###
