"""remove_scene_quality_score_fk

Revision ID: ac66dee829e6
Revises: 25a8497bf2cb
Create Date: 2026-01-31 21:20:18.900955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac66dee829e6'
down_revision: Union[str, Sequence[str], None] = '25a8497bf2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scene_quality_scores_storyboard_id_fkey'), 'scene_quality_scores', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('scene_quality_scores_storyboard_id_fkey'), 'scene_quality_scores', 'storyboards', ['storyboard_id'], ['id'])
    # ### end Alembic commands ###
