"""add_classification_rules_table

Revision ID: c1fe90c80b65
Revises: f1g2h3i4j5k6
Create Date: 2026-01-25 19:45:06.714274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fe90c80b65'
down_revision: Union[str, Sequence[str], None] = 'f1g2h3i4j5k6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.String(length=100), nullable=False),
    sa.Column('target_group', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_type', 'pattern')
    )
    op.create_index('idx_classification_rules_active', 'classification_rules', ['active'], unique=False)
    op.create_index('idx_classification_rules_group', 'classification_rules', ['target_group'], unique=False)
    op.add_column('tags', sa.Column('classification_source', sa.String(length=20), nullable=True))
    op.add_column('tags', sa.Column('classification_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'classification_confidence')
    op.drop_column('tags', 'classification_source')
    op.drop_index('idx_classification_rules_group', table_name='classification_rules')
    op.drop_index('idx_classification_rules_active', table_name='classification_rules')
    op.drop_table('classification_rules')
    # ### end Alembic commands ###
