"""baseline

Revision ID: c7a12c201195
Revises: 
Create Date: 2026-01-24 12:30:16.737862

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7a12c201195'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tags
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('group_name', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('exclusive', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index('idx_tags_category', 'tags', ['category'], unique=False)
    op.create_index('idx_tags_group', 'tags', ['group_name'], unique=False)

    # Tag Rules
    op.create_table('tag_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rule_type', sa.String(length=20), nullable=False),
        sa.Column('source_tag_id', sa.Integer(), nullable=True),
        sa.Column('target_tag_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['source_tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rule_type', 'source_tag_id', 'target_tag_id')
    )

    # Synonyms
    op.create_table('synonyms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.Column('synonym', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag_id', 'synonym')
    )

    # LoRAs
    op.create_table('loras',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=True),
        sa.Column('civitai_id', sa.Integer(), nullable=True),
        sa.Column('civitai_url', sa.String(length=500), nullable=True),
        sa.Column('trigger_words', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('default_weight', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('weight_min', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('weight_max', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('base_models', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('character_defaults', JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('recommended_negative', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('preview_image_url', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index('idx_loras_civitai', 'loras', ['civitai_id'], unique=False)

    # Characters
    op.create_table('characters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('identity_tags', sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column('clothing_tags', sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column('lora_id', sa.Integer(), nullable=True),
        sa.Column('lora_weight', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('preview_image_url', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['lora_id'], ['loras.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_index('idx_loras_civitai', table_name='loras')
    op.drop_table('loras')
    op.drop_table('synonyms')
    op.drop_table('tag_rules')
    op.drop_index('idx_tags_group', table_name='tags')
    op.drop_index('idx_tags_category', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###