"""baseline

Revision ID: c7a12c201195
Revises: 
Create Date: 2026-01-24 12:30:16.737862

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c7a12c201195'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
