"""add_media_asset_refs_to_models

Revision ID: ca169902f4a4
Revises: 7bdbef2edb37
Create Date: 2026-01-31 11:09:07.808649

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ca169902f4a4'
down_revision: str | Sequence[str] | None = '7bdbef2edb37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('preview_image_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'media_assets', ['preview_image_asset_id'], ['id'])
    op.add_column('loras', sa.Column('preview_image_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loras', 'media_assets', ['preview_image_asset_id'], ['id'])
    op.add_column('projects', sa.Column('avatar_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'media_assets', ['avatar_asset_id'], ['id'])
    op.add_column('scenes', sa.Column('image_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenes', 'media_assets', ['image_asset_id'], ['id'])
    op.add_column('sd_models', sa.Column('preview_image_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sd_models', 'media_assets', ['preview_image_asset_id'], ['id'])
    op.add_column('storyboards', sa.Column('video_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'storyboards', 'media_assets', ['video_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storyboards', type_='foreignkey')
    op.drop_column('storyboards', 'video_asset_id')
    op.drop_constraint(None, 'sd_models', type_='foreignkey')
    op.drop_column('sd_models', 'preview_image_asset_id')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_column('scenes', 'image_asset_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'avatar_asset_id')
    op.drop_constraint(None, 'loras', type_='foreignkey')
    op.drop_column('loras', 'preview_image_asset_id')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'preview_image_asset_id')
    # ### end Alembic commands ###
