"""add_tag_effectiveness_table

Revision ID: d073d96eed09
Revises: b2c3d4e5f6g7
Create Date: 2026-01-24 19:33:32.134016

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd073d96eed09'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6g7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_effectiveness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('total_confidence', sa.Float(), nullable=False),
    sa.Column('effectiveness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_index('idx_tag_effectiveness_score', 'tag_effectiveness', ['effectiveness'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_effectiveness_score', table_name='tag_effectiveness')
    op.drop_table('tag_effectiveness')
    # ### end Alembic commands ###
