"""Add video_url and recent_videos_json to Storyboard

Revision ID: d4fc742b4bca
Revises: b1f2a3c4d5e6
Create Date: 2026-01-30 21:49:27.874414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4fc742b4bca'
down_revision: Union[str, Sequence[str], None] = 'b1f2a3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rules_pattern', 'classification_rules', ['rule_type', 'pattern'], unique=True)
    op.add_column('storyboards', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('storyboards', sa.Column('recent_videos_json', sa.Text(), nullable=True))
    op.alter_column('tag_filters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tag_filters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tag_filters_tag_name_key'), 'tag_filters', type_='unique')
    op.drop_index(op.f('ix_tag_filters_tag_name'), table_name='tag_filters')
    op.create_index(op.f('ix_tag_filters_tag_name'), 'tag_filters', ['tag_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_filters_tag_name'), table_name='tag_filters')
    op.create_index(op.f('ix_tag_filters_tag_name'), 'tag_filters', ['tag_name'], unique=False)
    op.create_unique_constraint(op.f('tag_filters_tag_name_key'), 'tag_filters', ['tag_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tag_filters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tag_filters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('storyboards', 'recent_videos_json')
    op.drop_column('storyboards', 'video_url')
    op.drop_index('idx_rules_pattern', table_name='classification_rules')
    # ### end Alembic commands ###
