"""add character custom prompt fields

Revision ID: df9af51fe523
Revises: 1764bb5dfc16
Create Date: 2026-01-27 18:04:31.950607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9af51fe523'
down_revision: Union[str, Sequence[str], None] = '1764bb5dfc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('custom_base_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('custom_negative_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'custom_negative_prompt')
    op.drop_column('characters', 'custom_base_prompt')
    # ### end Alembic commands ###
