"""make_activity_log_storyboard_nullable_and_remove_fk

Revision ID: ec0ed3c9015d
Revises: d659ca13e2ce
Create Date: 2026-01-31 21:13:03.564601

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec0ed3c9015d"
down_revision: str | Sequence[str] | None = "d659ca13e2ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scenes", "use_reference_only", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("1")
    )
    op.alter_column(
        "scenes",
        "reference_only_weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.5"),
    )
    op.alter_column(
        "scenes",
        "environment_reference_weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.3"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scenes",
        "environment_reference_weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.3"),
    )
    op.alter_column(
        "scenes",
        "reference_only_weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.5"),
    )
    op.alter_column(
        "scenes", "use_reference_only", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("1")
    )
    # ### end Alembic commands ###
