"""convert_media_asset_to_polymorphic

Revision ID: ee73c749faa9
Revises: 4249c8f1cd5c
Create Date: 2026-01-31 12:06:19.484548

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee73c749faa9'
down_revision: str | Sequence[str] | None = '4249c8f1cd5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('owner_type', sa.String(length=50), nullable=True))
    op.add_column('media_assets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('is_temp', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.create_index(op.f('ix_media_assets_is_temp'), 'media_assets', ['is_temp'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_type'), 'media_assets', ['owner_type'], unique=False)
    op.drop_constraint(op.f('media_assets_storyboard_id_fkey'), 'media_assets', type_='foreignkey')
    op.drop_constraint(op.f('media_assets_project_id_fkey'), 'media_assets', type_='foreignkey')
    op.drop_constraint(op.f('media_assets_scene_id_fkey'), 'media_assets', type_='foreignkey')
    op.drop_column('media_assets', 'project_id')
    op.drop_column('media_assets', 'scene_id')
    op.drop_column('media_assets', 'storyboard_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('storyboard_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_assets', sa.Column('scene_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_assets', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('media_assets_scene_id_fkey'), 'media_assets', 'scenes', ['scene_id'], ['id'])
    op.create_foreign_key(op.f('media_assets_project_id_fkey'), 'media_assets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('media_assets_storyboard_id_fkey'), 'media_assets', 'storyboards', ['storyboard_id'], ['id'])
    op.drop_index(op.f('ix_media_assets_owner_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_is_temp'), table_name='media_assets')
    op.drop_column('media_assets', 'is_temp')
    op.drop_column('media_assets', 'owner_id')
    op.drop_column('media_assets', 'owner_type')
    # ### end Alembic commands ###
