"""Initial Pure V3 Baseline

Revision ID: f691fbaa1e51
Revises:
Create Date: 2026-01-28 22:28:04.684329

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f691fbaa1e51"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=200), nullable=True),
        sa.Column("scene_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("sd_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("match_rate", sa.Float(), nullable=True),
        sa.Column("tags_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_logs_character_id"), "activity_logs", ["character_id"], unique=False)
    op.create_index(op.f("ix_activity_logs_is_favorite"), "activity_logs", ["is_favorite"], unique=False)
    op.create_index(op.f("ix_activity_logs_match_rate"), "activity_logs", ["match_rate"], unique=False)
    op.create_index(op.f("ix_activity_logs_project_name"), "activity_logs", ["project_name"], unique=False)
    op.create_index(op.f("ix_activity_logs_scene_id"), "activity_logs", ["scene_id"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("loras", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommended_negative", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("custom_base_prompt", sa.Text(), nullable=True),
        sa.Column("custom_negative_prompt", sa.Text(), nullable=True),
        sa.Column("reference_base_prompt", sa.Text(), nullable=True),
        sa.Column("reference_negative_prompt", sa.Text(), nullable=True),
        sa.Column("preview_image_url", sa.String(length=500), nullable=True),
        sa.Column("prompt_mode", sa.String(length=20), nullable=False),
        sa.Column("ip_adapter_weight", sa.Float(), nullable=True),
        sa.Column("ip_adapter_model", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("embedding_type", sa.String(length=50), nullable=False),
        sa.Column("trigger_word", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "loras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("lora_type", sa.String(length=20), nullable=True),
        sa.Column("trigger_words", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("default_weight", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("gender_locked", sa.String(length=10), nullable=True),
        sa.Column("civitai_id", sa.Integer(), nullable=True),
        sa.Column("civitai_url", sa.String(length=500), nullable=True),
        sa.Column("preview_image_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_loras_civitai", "loras", ["civitai_id"], unique=False)
    op.create_table(
        "sd_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("model_type", sa.String(length=50), nullable=False),
        sa.Column("base_model", sa.String(length=50), nullable=True),
        sa.Column("civitai_id", sa.Integer(), nullable=True),
        sa.Column("civitai_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("preview_image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "storyboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_character_id", sa.Integer(), nullable=True),
        sa.Column("default_style_profile_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ko_name", sa.String(length=100), nullable=True),
        sa.Column("default_layer", sa.Integer(), nullable=False),
        sa.Column("usage_scope", sa.String(length=20), nullable=False),
        sa.Column("wd14_count", sa.Integer(), nullable=False),
        sa.Column("wd14_category", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_tags_layer", "tags", ["default_layer"], unique=False)
    op.create_table(
        "character_tags",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_permanent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id", "tag_id"),
    )
    op.create_table(
        "scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("storyboard_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["storyboard_id"],
            ["storyboards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenes_storyboard_id"), "scenes", ["storyboard_id"], unique=False)
    op.create_table(
        "style_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sd_model_id", sa.Integer(), nullable=True),
        sa.Column("loras", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("negative_embeddings", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("positive_embeddings", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("default_positive", sa.Text(), nullable=True),
        sa.Column("default_negative", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sd_model_id"],
            ["sd_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scene_character_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scene_tags",
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("scene_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scene_tags")
    op.drop_table("scene_character_actions")
    op.drop_table("style_profiles")
    op.drop_index(op.f("ix_scenes_storyboard_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_table("character_tags")
    op.drop_index("idx_tags_layer", table_name="tags")
    op.drop_table("tags")
    op.drop_table("storyboards")
    op.drop_table("sd_models")
    op.drop_index("idx_loras_civitai", table_name="loras")
    op.drop_table("loras")
    op.drop_table("embeddings")
    op.drop_table("characters")
    op.drop_index(op.f("ix_activity_logs_scene_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_project_name"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_match_rate"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_is_favorite"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_character_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
