from __future__ import annotations

from .db_cache import TagFilterCache

# --- Category suggestion patterns ---
CATEGORY_PATTERNS: dict[str, list[str]] = {
    "quality": [
        "masterpiece",
        "best_quality",
        "high_quality",
        "amazing_quality",
        "very_aesthetic",
        "absurdres",
        "highres",
        "incredibly_absurdres",
        "8k",
        "4k",
        "detailed",
        "ultra_detailed",
        "extremely_detailed",
        "intricate_details",
        "official_art",
        "anime_coloring",
        "perfect_lighting",
        # Realistic quality (photorealistic is in "style" category)
        "raw_photo",
        "sharp_focus",
        "film_grain",
        "dslr",
        "8k_uhd",
    ],
    "subject": [
        "1girl",
        "2girls",
        "3girls",
        "4girls",
        "5girls",
        "6+girls",
        "1boy",
        "2boys",
        "3boys",
        "4boys",
        "5boys",
        "6+boys",
        "solo",
        "duo",
        "trio",
        "group",
        "crowd",
        "everyone",
        "multiple_girls",
        "multiple_boys",
        "couple",
        "1other",
    ],
    "identity": ["male", "female", "androgynous"],
    "hair_color": [
        "black_hair",
        "blonde_hair",
        "brown_hair",
        "red_hair",
        "blue_hair",
        "green_hair",
        "pink_hair",
        "purple_hair",
        "white_hair",
        "silver_hair",
        "grey_hair",
        "gray_hair",
        "orange_hair",
        "aqua_hair",
        "light_brown_hair",
        "multicolored_hair",
        "gradient_hair",
        "streaked_hair",
        "two-tone_hair",
        "colored_inner_hair",
    ],
    "hair_length": [
        "short_hair",
        "medium_hair",
        "long_hair",
        "very_long_hair",
        "absurdly_long_hair",
        "shoulder-length_hair",
        "bald",
    ],
    "hair_style": [
        "bangs",
        "blunt_bangs",
        "side_bangs",
        "parted_bangs",
        "swept_bangs",
        "ponytail",
        "high_ponytail",
        "low_ponytail",
        "side_ponytail",
        "twintails",
        "low_twintails",
        "short_twintails",
        "braid",
        "braided_ponytail",
        "twin_braids",
        "side_braid",
        "french_braid",
        "bun",
        "double_bun",
        "hair_bun",
        "side_bun",
        "bob_cut",
        "hime_cut",
        "pixie_cut",
        "drill_hair",
        "ahoge",
        "antenna_hair",
        "sidelocks",
        "hair_over_one_eye",
        "hair_between_eyes",
        "hair_over_shoulder",
        "messy_hair",
        "straight_hair",
        "curly_hair",
        "wavy_hair",
        "spiked_hair",
        "spiky_hair",
        "slicked_back_hair",
    ],
    "hair_accessory": [
        "hairclip",
        "hairpin",
        "hair_ornament",
        "hair_flower",
        "hairband",
        "headband",
        "hair_ribbon",
        "hair_bow",
        "scrunchie",
        "hair_tie",
        "hair_stick",
        "crown",
        "tiara",
        "headpiece",
    ],
    "eye_color": [
        "blue_eyes",
        "red_eyes",
        "green_eyes",
        "brown_eyes",
        "purple_eyes",
        "yellow_eyes",
        "orange_eyes",
        "pink_eyes",
        "aqua_eyes",
        "golden_eyes",
        "amber_eyes",
        "grey_eyes",
        "heterochromia",
        "multicolored_eyes",
        "glowing_eyes",
    ],
    "skin_color": [
        "pale_skin",
        "dark_skin",
        "tanned_skin",
        "tanned",
        "white_skin",
        "brown_skin",
        "fair_skin",
        "light_skin",
        "dark-skinned",
        "light-skinned",
    ],
    "body_feature": [
        "pointy_ears",
        "elf_ears",
        "animal_ears",
        "cat_ears",
        "dog_ears",
        "fox_ears",
        "rabbit_ears",
        "wolf_ears",
        "horns",
        "demon_horns",
        "dragon_horns",
        "wings",
        "angel_wings",
        "demon_wings",
        "fairy_wings",
        "tail",
        "cat_tail",
        "fox_tail",
        "demon_tail",
        "halo",
        "fang",
        "fangs",
    ],
    "appearance": [
        "freckles",
        "mole",
        "beauty_mark",
        "scar",
        "tattoo",
        "piercing",
        "ear_piercing",
        "facial_mark",
        "makeup",
        "lipstick",
        "eyeshadow",
        "mascara",
    ],
    "body_type": [
        "slim",
        "petite",
        "tall",
        "short",
        "muscular",
        "chubby",
        "abs",
        "muscles",
        "bishounen",
        "bishoujo",
        "ikemen",
    ],
    "clothing_top": [
        "shirt",
        "t-shirt",
        "blouse",
        "sweater",
        "hoodie",
        "jacket",
        "coat",
        "blazer",
        "cardigan",
        "vest",
        "tank_top",
        "crop_top",
        "tube_top",
        "camisole",
        "black_tank_top",
        "white_tank_top",
        "green_hoodie",
        "black_hoodie",
        "white_hoodie",
    ],
    "clothing_bottom": [
        "skirt",
        "miniskirt",
        "long_skirt",
        "pleated_skirt",
        "pants",
        "jeans",
        "shorts",
        "leggings",
        "white_shorts",
        "black_shorts",
        "denim_shorts",
    ],
    "clothing_outfit": [
        "dress",
        "sundress",
        "wedding_dress",
        "evening_dress",
        "uniform",
        "school_uniform",
        "sailor_uniform",
        "maid_outfit",
        "suit",
        "tuxedo",
        "kimono",
        "yukata",
        "chinese_clothes",
        "swimsuit",
        "one-piece_swimsuit",
        "bikini",
        "school_swimsuit",
        "apron",
        "overalls",
    ],
    "clothing_detail": [
        "sleeveless",
        "short_sleeves",
        "long_sleeves",
        "wide_sleeves",
        "puffy_sleeves",
        "off_shoulder",
        "off-shoulder",
        "bare_shoulders",
        "collar",
        "tie",
        "necktie",
        "bowtie",
        "bow",
        "button",
        "zipper",
        "pocket",
        "belt",
        "ribbon",
        "lace",
        "frills",
        "open_clothes",
        "open_jacket",
        "open_shirt",
        "hood",
        "hood_up",
        "hood_down",
        "plaid",
        "striped",
    ],
    "legwear": [
        "socks",
        "thighhighs",
        "kneehighs",
        "pantyhose",
        "stockings",
        "fishnet",
        "bare_legs",
        "black_thighhighs",
        "white_thighhighs",
        "thigh_strap",
        "garter",
        "garter_belt",
    ],
    "footwear": [
        "barefoot",
        "shoes",
        "boots",
        "sneakers",
        "sandals",
        "high_heels",
        "loafers",
        "slippers",
        "mary_janes",
        "footwear",
        "brown_footwear",
        "black_footwear",
        "white_footwear",
    ],
    "accessory": [
        "glasses",
        "sunglasses",
        "hat",
        "cap",
        "beret",
        "gloves",
        "scarf",
        "bag",
        "backpack",
        "purse",
        "earrings",
        "necklace",
        "bracelet",
        "ring",
        "choker",
        "jewelry",
    ],
    "expression": [
        "smile",
        "smiling",
        "grin",
        "smirk",
        "laugh",
        "laughing",
        "happy",
        "sad",
        "crying",
        "tears",
        "frown",
        "sobbing",
        "angry",
        "annoyed",
        "frustrated",
        "glare",
        "surprised",
        "shocked",
        "scared",
        "frightened",
        "embarrassed",
        "shy",
        "blush",
        "blushing",
        "nervous",
        "serious",
        "expressionless",
        "deadpan",
        "stoic",
        "sleepy",
        "tired",
        "exhausted",
        "yawning",
        "excited",
        "cheerful",
        "joyful",
        "open_mouth",
        "closed_mouth",
        "parted_lips",
        "tongue",
        "tongue_out",
        "licking_lips",
        "pout",
        "pouting",
        ":o",
        ":d",
        ";)",
        "sweat",
        "sweatdrop",
        "nosebleed",
        "drool",
        "drooling",
        "teardrop",
        "confused",
        "curious",
    ],
    "gaze": [
        "looking_at_viewer",
        "looking_away",
        "looking_up",
        "looking_down",
        "looking_back",
        "looking_to_the_side",
        "looking_afar",
        "looking_ahead",
        "sideways_glance",
        "averting_eyes",
        "averted_gaze",
        "eye_contact",
        "eyes_closed",
        "closed_eyes",
        "half-closed_eyes",
        "squinting",
        "one_eye_closed",
        "wink",
        "winking",
        "staring",
        "glancing",
        "downcast_eyes",
        "empty_eyes",
        "sparkling_eyes",
        "heart-shaped_pupils",
    ],
    "pose": [
        "standing",
        "sitting",
        "kneeling",
        "crouching",
        "squatting",
        "lying",
        "lying_down",
        "on_back",
        "on_stomach",
        "on_side",
        "leaning",
        "leaning_forward",
        "leaning_back",
        "reclining",
        "lounging",
        "sprawling",
        "arms_crossed",
        "arms_behind_back",
        "arms_up",
        "arms_at_sides",
        "hand_on_hip",
        "hands_on_hips",
        "hands_together",
        "hand_up",
        "hands_up",
        "arm_up",
        "hand_on_chest",
        "hand_on_face",
        "hand_on_head",
        "v",
        "peace_sign",
        "thumbs_up",
        "crossed_legs",
        "spread_legs",
        "legs_together",
        "one_leg_raised",
        "leg_up",
        "profile",
        "back",
        "turned_around",
        "curled_up",
        "fetal_position",
    ],
    "action_body": [
        "walking",
        "running",
        "jumping",
        "flying",
        "swimming",
        "diving",
        "dancing",
        "stretching",
        "bending",
        "turning",
        "fighting",
        "kicking",
        "punching",
    ],
    "action_hand": [
        "holding",
        "holding_bag",
        "holding_book",
        "holding_cup",
        "holding_phone",
        "holding_umbrella",
        "holding_weapon",
        "holding_food",
        "holding_flower",
        "holding_hands",
        "holding_sword",
        "holding_gun",
        "holding_knife",
        "grabbing",
        "reaching",
        "pointing",
        "waving",
        "hugging",
        "embracing",
        "carrying",
    ],
    "action_daily": [
        "reading",
        "writing",
        "drawing",
        "typing",
        "using_phone",
        "eating",
        "drinking",
        "cooking",
        "baking",
        "singing",
        "playing_instrument",
        "playing_guitar",
        "playing_piano",
        "gaming",
        "playing_game",
        "sleeping",
        "napping",
        "resting",
        "bathing",
        "showering",
        "dressing",
        "undressing",
    ],
    "camera": [
        "close-up",
        "closeup",
        "extreme_close-up",
        "face_focus",
        "portrait",
        "upper_body",
        "cowboy_shot",
        "thigh_focus",
        "hip_focus",
        "full_body",
        "long_shot",
        "wide_shot",
        "very_wide_shot",
        "from_above",
        "from_below",
        "from_side",
        "from_behind",
        "dutch_angle",
        "tilted_frame",
        "low_angle",
        "high_angle",
        "bird's_eye_view",
        "worm's_eye_view",
        "straight-on",
        "front_view",
        "side_view",
        "back_view",
        "pov",
        "first_person_view",
        "over_shoulder",
        "depth_of_field",
        "bokeh",
        "motion_blur",
        "lens_flare",
        "out_of_frame",
        "cropped",
        "partially_visible",
    ],
    "location_indoor_general": [
        "indoors",
    ],
    "location_indoor_specific": [
        # Specific indoor locations (mutually exclusive)
        "bedroom",
        "living_room",
        "kitchen",
        "bathroom",
        "classroom",
        "library",
        "office",
        "study",
        "cafe",
        "restaurant",
        "bar",
        "shop",
        "store",
        "convenience_store",
        "train",
        "bus",
        "car_interior",
        "airplane",
        "hospital",
        "church",
        "temple",
        "shrine",
        "gym",
        "pool",
        "locker_room",
        "laboratory",
        "lab",
        "science_lab",
        "spaceship",
    ],
    "environment": [
        "shelf",
        "bookshelf",
        "desk",
        "table",
        "chair",
        "sofa",
        "couch",
        "bed",
        "pillow",
        "blanket",
        "curtain",
        "window",
        "door",
        "stairs",
        "floor",
        "wall",
        "ceiling",
        "lamp",
        "chandelier",
        "mirror",
        "computer",
        "monitor",
        "keyboard",
        "laptop",
        "phone",
        "smartphone",
        "television",
        "tv",
        "screen",
        "plate",
        "cup",
        "mug",
        "bowl",
        "utensils",
        "fork",
        "spoon",
        "knife",
        "food",
        "drink",
        "bottle",
        "glass",
        "potted_plant",
        "flower",
        "plant",
        "vase",
        "flowers",
        "tiles",
        "brick",
        "concrete",
        "wood_floor",
        "carpet",
    ],
    "location_outdoor": [
        "outdoors",
        "outside",
        "exterior",
        "street",
        "alley",
        "sidewalk",
        "crosswalk",
        "park",
        "garden",
        "yard",
        "playground",
        "forest",
        "woods",
        "jungle",
        "meadow",
        "field",
        "beach",
        "ocean",
        "sea",
        "lake",
        "river",
        "waterfall",
        "pond",
        "water",
        "mountain",
        "hill",
        "cliff",
        "valley",
        "mountainous_horizon",
        "city",
        "town",
        "village",
        "rooftop",
        "balcony",
        "bridge",
        "pier",
        "dock",
        "neon_city",
        "space",
    ],
    "background_type": [
        "simple_background",
        "white_background",
        "black_background",
        "grey_background",
        "gray_background",
        "gradient_background",
        "blurry_background",
        "detailed_background",
        "abstract_background",
        "no_background",
        "transparent_background",
        "starry_background",
        "floral_background",
        "machine_background",
        "mechanical_background",
    ],
    "time_of_day": [
        "day",
        "daytime",
        "morning",
        "afternoon",
        "night",
        "nighttime",
        "midnight",
        "evening",
        "sunset",
        "sunrise",
        "dusk",
        "dawn",
        "twilight",
        "golden_hour",
        "blue_hour",
    ],
    "weather": [
        "sunny",
        "cloudy",
        "overcast",
        "rainy",
        "rain",
        "snowy",
        "snow",
        "foggy",
        "fog",
        "misty",
        "stormy",
        "thunder",
        "lightning",
        "windy",
    ],
    "particle": [
        "falling_leaves",
        "falling_petals",
        "cherry_blossoms",
        "floating_particles",
        "dust_particles",
        "fireflies",
        "bubbles",
        "sparkles",
        "confetti",
    ],
    "lighting": [
        "natural_light",
        "sunlight",
        "moonlight",
        "starlight",
        "backlighting",
        "backlit",
        "rim_light",
        "rim_lighting",
        "dramatic_lighting",
        "cinematic_lighting",
        "studio_lighting",
        "soft_lighting",
        "harsh_lighting",
        "ambient_lighting",
        "neon_lights",
        "neon",
        "glowing",
        "light_rays",
        "shadow",
        "shadows",
        "dark",
        "bright",
        "warm_lighting",
        "cold_lighting",
        "golden_light",
    ],
    "mood": [
        "romantic",
        "melancholic",
        "melancholy",
        "peaceful",
        "serene",
        "calm",
        "tense",
        "dramatic",
        "intense",
        "epic",
        "mysterious",
        "eerie",
        "creepy",
        "horror",
        "ethereal",
        "magical",
        "fantastical",
        "dreamy",
        "nostalgic",
        "bittersweet",
        "wistful",
        "cozy",
        "comfortable",
        "warm",
        "intimate",
        "lonely",
        "isolated",
        "solitary",
        "gloomy",
        "somber",
        "moody",
        "futuristic",
        "cyberpunk",
        "sci-fi",
        "steampunk",
        "post-apocalyptic",
        # 감정 기반 mood (Gemini 생성 빈도 높음)
        "anxious",
        "nervous",
        "hopeful",
        "happy",
        "cheerful",
        "joyful",
        "overjoyed",
        "surprised",
        "curious",
        "focused",
        "determined",
        "proud",
        "competitive",
        "reluctant",
        "struggling",
        "uplifted",
        "awe",
        "wonder",
        "longing",
    ],
    "style": [
        "anime",
        "manga",
        "realistic",
        "photorealistic",
        "semi-realistic",
        "sketch",
        "lineart",
        "ink",
        "watercolor",
        "oil_painting",
        "digital_art",
        "cel_shading",
        "flat_color",
        "soft_shading",
        "chibi",
        "super_deformed",
        "kemonomimi_mode",
        "monochrome",
        "greyscale",
        "sepia",
        "pixel_art",
        "voxel",
        "3d",
    ],
}

CATEGORY_PRIORITY: dict[str, int] = {
    "quality": 1,
    "subject": 2,
    "identity": 3,
    "hair_color": 4,
    "hair_length": 4,
    "hair_style": 4,
    "hair_accessory": 4,
    "eye_color": 4,
    "skin_color": 4,
    "body_feature": 4,
    "appearance": 4,
    "body_type": 4,
    "clothing_top": 5,
    "clothing_bottom": 5,
    "clothing_outfit": 5,
    "clothing_detail": 5,
    "legwear": 5,
    "footwear": 5,
    "accessory": 5,
    "expression": 6,
    "gaze": 7,
    "pose": 8,
    "action_body": 9,
    "action_hand": 9,
    "action_daily": 9,
    "camera": 10,
    "location_indoor_specific": 11,
    "location_outdoor": 11,
    "environment": 11,
    "location_indoor_general": 12,
    "background_type": 12,
    "time_of_day": 13,
    "weather": 13,
    "particle": 13,
    "lighting": 14,
    "mood": 15,
    "style": 16,
}

# ── group_name → 12-Layer 매핑 (SSOT) ────────────────────────────────
# composition._infer_layer_from_pattern() 와 sync.py 양쪽에서 참조
GROUP_NAME_TO_LAYER: dict[str, int] = {
    "quality": 0,  # LAYER_QUALITY
    "subject": 1,  # LAYER_SUBJECT
    "identity": 2,  # LAYER_IDENTITY
    "hair_color": 2,  # LAYER_IDENTITY
    "hair_length": 2,  # LAYER_IDENTITY
    "hair_style": 2,  # LAYER_IDENTITY
    "hair_accessory": 6,  # LAYER_ACCESSORY
    "eye_color": 2,  # LAYER_IDENTITY
    "eye_detail": 2,  # LAYER_IDENTITY
    "skin_color": 3,  # LAYER_BODY
    "body_feature": 3,  # LAYER_BODY
    "appearance": 3,  # LAYER_BODY
    "body_type": 3,  # LAYER_BODY
    "clothing_top": 4,  # LAYER_MAIN_CLOTH
    "clothing_bottom": 4,  # LAYER_MAIN_CLOTH
    "clothing_outfit": 4,  # LAYER_MAIN_CLOTH
    "clothing": 4,  # LAYER_MAIN_CLOTH (coarse alias)
    "clothing_detail": 5,  # LAYER_DETAIL_CLOTH
    "legwear": 5,  # LAYER_DETAIL_CLOTH
    "footwear": 5,  # LAYER_DETAIL_CLOTH
    "accessory": 6,  # LAYER_ACCESSORY
    "expression": 7,  # LAYER_EXPRESSION
    "gaze": 7,  # LAYER_EXPRESSION
    "pose": 8,  # LAYER_ACTION
    "action_body": 8,  # LAYER_ACTION
    "action_hand": 8,  # LAYER_ACTION
    "action_daily": 8,  # LAYER_ACTION
    "action": 8,  # LAYER_ACTION (coarse alias)
    "gesture": 8,  # LAYER_ACTION (coarse alias)
    "camera": 9,  # LAYER_CAMERA
    "location_indoor_general": 10,  # LAYER_ENVIRONMENT
    "location_indoor_specific": 10,  # LAYER_ENVIRONMENT
    "location_indoor": 10,  # LAYER_ENVIRONMENT (coarse alias)
    "location_outdoor": 10,  # LAYER_ENVIRONMENT
    "environment": 10,  # LAYER_ENVIRONMENT
    "background_type": 10,  # LAYER_ENVIRONMENT
    "time_of_day": 10,  # LAYER_ENVIRONMENT
    "time_weather": 10,  # LAYER_ENVIRONMENT (coarse alias)
    "weather": 10,  # LAYER_ENVIRONMENT
    "particle": 10,  # LAYER_ENVIRONMENT
    "lighting": 11,  # LAYER_ATMOSPHERE
    "mood": 11,  # LAYER_ATMOSPHERE
    "style": 11,  # LAYER_ATMOSPHERE
}


def suggest_category_for_tag(tag: str) -> tuple[str, float]:
    """Suggest a category for a tag based on patterns."""
    # Always normalize to underscores for Danbooru standard
    normalized = tag.lower().replace(" ", "_").strip()
    if normalized in TagFilterCache.get_skip_tags():
        return ("skip", 1.0)

    best_category = ""
    best_score = 0.0
    # Search with underscores directly
    for category, patterns in CATEGORY_PATTERNS.items():
        if normalized in patterns:
            return (category, 1.0)

    # Fallback to word subset matching (using underscores for internal comparison)
    normalized_words = set(normalized.split("_"))
    for category, patterns in CATEGORY_PATTERNS.items():
        for pattern in patterns:
            pattern_words = set(pattern.split("_"))
            if pattern_words.issubset(normalized_words):
                score = 0.95
                if score > best_score:
                    best_score, best_category = score, category
            elif normalized_words.issubset(pattern_words) and len(normalized) >= 4:
                score = 0.9
                if score > best_score:
                    best_score, best_category = score, category

    return (best_category, best_score) if best_category else ("", 0.0)
